---
  - name: install htop
    apt: 
      pkg: htop 
      state: latest
      update_cache: true

  - name: install virtualenv
    apt: 
      pkg: virtualenv
      state: latest
      update_cache: false

  - name: install python-pip
    apt: 
      pkg: python-pip
      state: latest
      update_cache: false  

  - name: install python-dbus
    apt: 
      pkg: python-dbus
      state: latest
      update_cache: false

  - name: install git
    apt: 
      pkg: git 
      state: latest 
      update_cache: false

  - name: install build-essential
    apt: 
      pkg: build-essential 
      state: latest 
      update_cache: false

  - name: install python-dev
    apt: 
      pkg: python-dev 
      state: latest 
      update_cache: false


- name: Pull from Github
  git:
        repo: https://github.com/GTez/pi-watcher.git
        dest: /opt/pi-watcher
        accept_hostkey: yes

- name: Get Python Modules
  pip:
    requirements: /opt/requirements.txt
    virtualenv: /opt/pi-watcher/venv


- name: Ensure Directory has correct permissions
  file:
    path: /opt/pi-watcher
    state: directory
    mode: "a+w"
    recurse: yes
    owner: root

- name: Copy systemd service
  copy:
    remote_src: yes
    src: /opt/pi-watcher/config/systemd/system/gunicorn.service
    dest: /etc/systemd/system/

- name: Enable systemd
  systemd:
    name: gunicorn.service
    enabled: yes
    state: started