- hosts: all
  gather_facts: yes

  roles:
    - base
    - { role: geerlingguy.nginx }

  post_tasks:

    - name: reboot
      shell: reboot

    - name: waiting for server to return
      local_action: wait_for host={{ ansible_ssh_host }} state=started